[package]
name = "alpine-text-layout"
version.workspace = true
description = "Bounded visible text layout and monochrome glyph atlas for Alpine"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
alpine-text = { path = "../alpine-text", version = "=0.0.0" }

[lints]
workspace = true
